config/routes.rb
PipeCleaner::Application.routes.draw do


	resources :notifications do
		collection do
			get 'user', as: :user_notifications
			put 'user_update', as: :user_notifications_update
		end

	end


	resources :services do
		member do
			get 'test'
		end
	end
	
	resources :favorites
	resources :delayed_jobs

	match "/documents/:file_or_folder", :controller => :documents, :action => :get_file, :file_or_folder => /.*/
	resources :documents, :only => :get_file

	devise_for :users
	resources :users

	get 'manage' => 'users#manage'

	resources :pipelines do
		member do
			get 'reports'
		end
		resources :stages do
		  resources :triggers
		end
		member do
			put	'reorder'
			get 'overview'
			get 'status'
			get 'statistics'
			get 'recent'
			put 'active'
			get 'batch'
			post 'batch' => 'pipelines#submit_batch', as: :submit_batch
			post 'favorite'
			delete 'unfavorite'
		end
		resources :members do
			member do
				put 'archive'
				put 'unarchive'
			end
		end
	end


	resources :statuses do
		collection do
			post 'advance'
			put	'ping'
		end
	end
	resources :items do
		member do
			put 'associate'
			put 'disassociate'
			get 'data'
		end
		collection do
			get 'find'
		end
	end
	resources :pipelines


	get 'welcome' => "welcome#landing",  as: 'landing'
	get 'dashboard' => "welcome#dashboard", as: 'dashboard'
	get 'api' => "welcome#api",  as: 'api'
	get 'integration' => "welcome#integration",  as: 'integration'
	get 'guide' => 'welcome#guide',	as: 'guide'
	get 'terms' => 'welcome#terms',	as: 'terms'
	get 'queue' => 'welcome#queue', as: 'queue'
	get 'mashup' => 'welcome#mashup', as: 'mashup'

	# User management.
	get 'manage' => 'users#manage'
	post 'manage/:user_id/deny' => 'users#deny', as: :deny_user
	post 'manage/:user_id/approve' => 'users#approve', as: :approve_user
	put  'manage/:user_id' => 'users#update', as: :update_user
	post 'manage/:user_id/transfer' => 'users#transfer', as: :transfer_ownership
	post 'manage/:user_id/regenerate_api_token' => 'users#regenerate', as: :regenerate

	root :to => "welcome#landing"

	# rails_admin
	mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'


end

app/models/service.rb
class Service < ActiveRecord::Base

	has_many	:triggers,	dependent: :destroy

	validates_presence_of	:name
	validates_presence_of	:url
	validates_presence_of	:verb

	validates_uniqueness_of	:name

	VERB_GET	= 'GET'
	VERB_HEAD	= 'HEAD'
	VERB_POST	= 'POST'
	VERB_PUT	= 'PUT'
	VERB_DELETE	= 'DELETE'

	ALLOWED_VERBS = [VERB_GET, VERB_HEAD, VERB_POST, VERB_PUT, VERB_DELETE]

	validates :verb, :inclusion => {:in => ALLOWED_VERBS}


	attr_accessible :include_basic, :include_data, :include_extended, :name, :url, :verb

	def notify(status, trigger = nil)
		resp = nil
		stage = status.stage

		# Sanity check the current conditions
		if trigger && trigger.condition == status.code
			payload = {}
			if self.include_basic
				stages = stage.pipeline.stages.sort{|a,b| a.number <=> b.number}
				previous = stages[stage.number - 1]
				current = stages[stage.number]
				nex = stages[stage.number + 1]
				payload[:status] = JSON.parse status.to_json(include: [:member, :stage])
				payload[:stage_name] = current.name
				payload[:item_name] = status.member.item.name
				payload[:pipeline_code] = stage.pipeline.code
				payload[:pipeline_name] = stage.pipeline.name
				payload[:previous_stage_id] = previous.id unless previous.nil?
				payload[:previous_stage_name] = previous.name unless previous.nil?
				payload[:next_stage_id] = nex.id unless nex.nil?
				payload[:next_stage_name] = nex.name unless nex.nil?
			end
			if self.include_extended
				payload[:member] = JSON.parse status.member.to_json(include: [:statuses, :item])
				payload[:pipeline] = JSON.parse status.stage.pipeline.to_json(include: [:stages])
			end
			if self.include_data
				data = {}
				begin
					data = JSON.parse(status.member.item.data)
				rescue
					puts "BUG: Why is there bad JSON in the database!?!?"
				end
				payload[:data] = data
			end
			h = {'Content-Type' => 'application/json'}
			body = payload.to_json
			puts "SENDING\n#{body}"
			case self.verb
			when VERB_GET
				resp = HTTParty.get(url, :body => body, headers: h)			
			when VERB_HEAD
				resp = HTTParty.head(url, :body => body, headers: h)			
			when VERB_POST
				resp = HTTParty.post(url, :body => body, headers: h)			
			when VERB_PUT
				resp = HTTParty.put(url, :body => body, headers: h)			
			when VERB_DELETE
				resp = HTTParty.delete(url, :body => body, headers: h)			
			end
		else
			# Either the trigger is not known, or the condition no longer matcher the applicable status code.
			# This can happen legitimately in the case where the status is updated multiple times in rapid succession
			# before asynchronous trigger processing jobs kick in.
		end

		resp
	end

end

app/controllers/services_controller.rb
class ServicesController < InheritedResources::Base

	before_filter :authenticate_user!
	load_and_authorize_resource

	def index
		@services = Service.paginate(:page => params[:page], :per_page => 2)

		respond_to do |format|
			format.html # index.html.erb
			format.json { render json: @services }
			format.xml { render xml: @services }
		end
	end

end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.slim
= form_for @service do |f|
	- if @service.errors.any?
		#error_explanation
			h2 = "#{pluralize(@service.errors.count, "error")} prohibited this service from being saved:"
			ul
				- @service.errors.full_messages.each do |message|
					li = message

	p.help-block
		| Use this form to quickly register a RESTful web service with PipeCleaner. If you want to 
		i create 
		| a service from scratch, or make an existing one compatible with PipeCleaner, see the 
		= link_to 'integration help', integration_path
		|  page instead!
	h3 Core Fields
	.control-group
		= f.label :name, :class => 'control-label'
		span.help-block Just a human-readable label shown throughout the system.
		.controls
			= f.text_field :name, required: true, placeholder: 'My Service'
	.control-group
		= f.label :url, :class => 'control-label'
		span.muted This is important as it needs to be the exact REST API URL of the service. It's probably something simple. Not that you may manually add a parameters to this URL via a "query string" at the end. This will be merged with any other content before making the service hit. Also note that this URL needs to be network-accessible by this instance of PipeCleaner. Just because you can hit the URL on your local machine doesn't necesarrily mean that PipeCleaner can hit it directly! If you get through service configuration and still aren't seeing the hit on the service side, you might want to enlist a network ninja to help troubleshoot.
		.controls
			= f.text_field :url, required: true, placeholder: 'http://example.com/foo'
	.control-group
		= f.label :verb, :class => 'control-label'
		span.help-block These are all the standard HTTP verbs. We require you to choose from this whitelist because not all verbs would make sense to PipeCleaner, or your service, so it doesn't make sense to list them all. If you're not getting a hit in your PipeCleaner-Compatible Service, make sure you are both configured on the correct path as well as the correct verb!
		.controls
			= f.select :verb, options_for_select(Service::ALLOWED_VERBS.collect{|v| [v,v]}), required: true
	h3 Optional Payload
	div.well
		p Request should include:
		.control-group
			label.checkbox
				= f.check_box :include_basic
				| Basic work item information.
		.control-group
			label.checkbox
				= f.check_box :include_extended
				| Extended work item statistics.
		.control-group
			label.checkbox
				= f.check_box :include_data
				| User-provided data objects.
	.form-actions
		= f.submit 'Save', :class => 'btn btn-primary'

app/views/services/edit.html.slim
h1
	| Editing service:  
	= @service.name
p
	= link_to 'view all services', services_path


== render 'form'

app/views/services/index.html.slim
- model_class = Service
div class="page-header"
	h1 All configured services.
	p
		| PipeCleaner has 
		= Service.count
		|  registered services.
   	= link_to "Register a service.", new_service_path, :class => 'btn btn-primary'

= will_paginate @services

table class="table table-striped table-condensed table-hover"
	thead
		tr
			th Name
			th Url
			th Verb
			th
				| Send Data:
				br
				| Basic / Extended / User
			th Triggers
			th Created
			th APIs
			th=t '.actions', :default => t("helpers.actions")
	tbody
	- @services.each do |service|
		tr
			td = service.name
			td = service.url
			td = service.verb
			td
				= check_box_tag :service, :include_basic, service.include_basic, disabled: true
				| &nbsp;
				= check_box_tag :service, :include_extended, service.include_extended, disabled: true
				| &nbsp;
				= check_box_tag :service, :include_data, service.include_data, disabled: true
			td = service.triggers.count
			td
				= time_ago_in_words service.created_at
				|  ago.
				br
				= service.created_at
			td
				= link_to 'JSON', service_url(service, format: 'json')
				|  
				= link_to 'XML', service_url(service, format: 'xml')
			td
				 / = link_to  'Test', test_service_path(service), :class => 'btn btn-mini', confirm: "This will issue a basic web service hit from a PipeCleaner server, and will include FAKE content for the options you've enabled. This is intended only for validating your service integrations."
				 = link_to  t('.edit', :default => t("helpers.links.edit")), edit_service_path(service), :class => 'btn btn-mini'
				 = link_to t('.destroy', :default => t("helpers.links.destroy")), service, :confirm => "This will also destroy all configured triggers to which this service is attached. This is irreversible, so if you want to use this service again you'll have to add it again. Are you sure?", :method => :delete, :class => 'btn btn-mini btn-danger'

= will_paginate @services

app/views/services/new.html.slim
h1 Register a service.

== render 'form'

= link_to 'Back', services_path

app/views/services/show.html.slim
p#notice = notice
= link_to 'view all services', services_path

h1 Service Overview
hr

.row-fluid

	.span6
		h2 Basics
		dl.dl-horizontal
			dt Name
			dd = @service.name
			dt Url
			dd = @service.url
			dt Verb
			dd = @service.verb
			dt Included data
			dd
				label.checkbox
					= check_box_tag :service, :include_basic, @service.include_basic, disabled: true
					| Basic
				label.checkbox
					= check_box_tag :service, :include_extended, @service.include_extended, disabled: true
					| Extended
				label.checkbox
					= check_box_tag :service, :include_data, @service.include_data, disabled: true
					| User defined
	
	.span6
		h2 Configured Triggers
		table.table.table-condensed.table-striped
			thead
				tr
					th Condition
					th Stage
					th Pipeline
			tbody
				- @service.triggers.all do |t|
					tr
						th t.condition
						th t.stage.name
						th t.stage.pipeline.name

						