config/routes.rb
PipeCleaner::Application.routes.draw do


	resources :notifications do
		collection do
			get 'user', as: :user_notifications
			put 'user_update', as: :user_notifications_update
		end

	end


	resources :services do
		member do
			get 'test'
		end
	end
	
	resources :favorites
	resources :delayed_jobs

	match "/documents/:file_or_folder", :controller => :documents, :action => :get_file, :file_or_folder => /.*/
	resources :documents, :only => :get_file

	devise_for :users
	resources :users

	get 'manage' => 'users#manage'

	resources :pipelines do
		member do
			get 'reports'
		end
		resources :stages do
		  resources :triggers
		end
		member do
			put	'reorder'
			get 'overview'
			get 'status'
			get 'statistics'
			get 'recent'
			put 'active'
			get 'batch'
			post 'batch' => 'pipelines#submit_batch', as: :submit_batch
			post 'favorite'
			delete 'unfavorite'
		end
		resources :members do
			member do
				put 'archive'
				put 'unarchive'
			end
		end
	end


	resources :statuses do
		collection do
			post 'advance'
			put	'ping'
		end
	end
	resources :items do
		member do
			put 'associate'
			put 'disassociate'
			get 'data'
		end
		collection do
			get 'find'
		end
	end
	resources :pipelines


	get 'welcome' => "welcome#landing",  as: 'landing'
	get 'dashboard' => "welcome#dashboard", as: 'dashboard'
	get 'api' => "welcome#api",  as: 'api'
	get 'integration' => "welcome#integration",  as: 'integration'
	get 'guide' => 'welcome#guide',	as: 'guide'
	get 'terms' => 'welcome#terms',	as: 'terms'
	get 'queue' => 'welcome#queue', as: 'queue'
	get 'mashup' => 'welcome#mashup', as: 'mashup'

	# User management.
	get 'manage' => 'users#manage'
	post 'manage/:user_id/deny' => 'users#deny', as: :deny_user
	post 'manage/:user_id/approve' => 'users#approve', as: :approve_user
	put  'manage/:user_id' => 'users#update', as: :update_user
	post 'manage/:user_id/transfer' => 'users#transfer', as: :transfer_ownership
	post 'manage/:user_id/regenerate_api_token' => 'users#regenerate', as: :regenerate

	root :to => "welcome#landing"

	# rails_admin
	mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'


end

app/models/pipeline.rb
class Pipeline < ActiveRecord::Base

	extend FriendlyId
	friendly_id	:code, use: :slugged

	has_many	:stages,	dependent: :destroy
	has_many	:members,	dependent: :destroy

	has_many	:items,	through: :members

	belongs_to	:user,	foreign_key: :created_by

	validates_presence_of	:name
	validates_presence_of	:description
	validates_presence_of	:code
	validates_presence_of	:user

	validates_uniqueness_of	:name
	validates_uniqueness_of	:code
	
	attr_accessible :code, :description, :name, :user

	def statistics
		stats = {}
		self.stages.rank(:number).each do |s|
			members = {}
			Status::ALL.each do |name|
				members[name] = []
			end
			self.members.each do |m|
				status = s.statuses.find {|stat| stat.member == m}
				# status = Status.where(member_id: m.id, stage_id: s.id).first
				if status.nil?
					members[Status::DEFAULT] << m
				else
					members[status.code] << m
				end
			end
			stats[s.name] = members
		end
		stats
	end

end

app/controllers/pipelines_controller.rb
class PipelinesController < InheritedResources::Base

	before_filter :authenticate_user!,  except: [:landing]
	load_and_authorize_resource


	def show
		@pipeline = Pipeline.friendly_id.find(params[:id])
		respond_to do |format|
			# format.html # show.html.erb
			format.json { render json: @pipeline, include: [:stages] }
			format.xml { render xml: @pipeline, include: [:stages] }
		end
	end

	def reports
		authorize!	:show, @pipeline
	end

	def batch
	end

	def submit_batch
		puts "P: #{@pipeline}"
		data = params[:data]
		project_tags = params[:project_tags]
		success = false
		added = []
		skipped = 0
		msg = nil
		begin
			puts "PARSING: #{data}"
			CSV.parse(data) do |row|
				puts "ROW: #{row}"
				if row[0].nil? || row[0] == ''
					puts "Empty line."
				else
					puts "ADDING: '#{row[0]}', '#{row[1]}'"
					item = Item.new(name: row[0], notes: row[1])
					item.user = current_user
					item.project_list = project_tags
					item.save
					if item.id.nil?
						skipped += 1
					else
						Member.create(pipeline_id: @pipeline.id, item_id: item.id)
						added << row[0]
					end
				end
			end
	 		msg = "Added #{added.count} work items to the #{@pipeline.name} pipeline. #{skipped} were skipped."
			success = true
		rescue Exception => e
			puts "E: #{e}"
			msg = "Your data couldn't be cleanly parsed, probably due to a synax error."
		end

	
		respond_to do |format|
		 	if success
				format.html { redirect_to dashboard_path, notice: msg }
		 	else
				format.html { render action: :batch, notice: msg}
		 	end
		end
	end

	def active
		@pipeline = Pipeline.find(params[:id])
		set_session_pipeline(@pipeline)
		respond_to do |format|
			format.json { head :no_content }
			format.xml { head :no_content }
		end
	end

	def overview
		@pipeline = Pipeline.find(params[:id], include: [:stages, :items])
		respond_to do |format|
			format.html{ render partial: 'overview', locals: {pipeline: @pipeline}, layout: false }
		end
	end
	def status
		@pipeline = Pipeline.find(params[:id])
		respond_to do |format|
			format.html{ render partial: 'status', locals: {pipeline: @pipeline}, layout: false }
		end
	end
	def statistics
		@pipeline = Pipeline.find(params[:id], include: [{stages: :statuses}, :items, :members])
		respond_to do |format|
			format.html{ render partial: 'statistics', locals: {pipeline: @pipeline}, layout: false }
		end
	end
	def recent
		@pipeline = Pipeline.find(params[:id])
		respond_to do |format|
			format.html{ render partial: 'recent', locals: {pipeline: @pipeline}, layout: false }
		end
	end

	def reorder
		@pipeline = Pipeline.find(params[:id])
		order = params[:order]
		order.each_with_index do |id, index|
			s = Stage.find(id)
			puts "SID #{s.id}, INDEX #{index}"
			if s.number != index
				s.number = index
				s.save!
				puts "SAVED!"
			end
		end
		respond_to do |format|
			if @pipeline.save
				format.json { head :no_content }
				format.xml { head :no_content }
			else
				format.json { render json: @pipeline.errors, status: :unprocessable_entity }
				format.xml { render xml: @pipeline.errors, status: :unprocessable_entity }
			end
		end
	end

	# GET /pipelines
	# GET /pipelines.json
	def index
		@pipelines = Pipeline.all(include: :stages)

		respond_to do |format|
			format.html # index.html.erb
			format.json { render json: @pipelines }
		end
	end


	def edit
		@pipeline = Pipeline.find(params[:id], include: [{stages: :triggers}])	
	end

	def create
		@pipeline = Pipeline.new(params[:pipeline])
		@pipeline.user = current_user
		create! { edit_pipeline_path(@pipeline) }
	end

	def update
		update! { edit_pipeline_path(@pipeline) }
	end



	def favorite
		@favorite = Favorite.new(member_id: params[:member_id], user_id: current_user.id)
		respond_to do |format|
			if @favorite.save
				# format.html { redirect_to @favorite, notice: 'Favorite was successfully created.' }
				format.json { render json: @favorite, status: :created, location: @favorite }
			else
				# format.html { render action: "new" }
				format.json { render json: @favorite.errors, status: :unprocessable_entity }
			end
		end
	end

	def unfavorite
		@favorite = Favorite.where(member_id: params[:member_id], user_id: current_user.id).first
		if @favorite
			@favorite.destroy
		end

		respond_to do |format|
			# format.html { redirect_to favorites_url }
			format.json { head :no_content }
		end
	end

end

app/helpers/pipelines_helper.rb
module PipelinesHelper
end

app/views/pipelines/_form.html.slim
= form_for @pipeline, :html => { :class => "form-horizontal" } do |f|

    .control-group
      = f.label :name, :class => 'control-label'
      .controls
        = f.text_field :name, required: true, placeholder: 'Order Processing'
        span class="help-block" Human-readable name.
    .control-group
      = f.label :code, :class => 'control-label'
      .controls
        = f.text_field :code, required: true, placeholder: 'orders'
        span class="help-block" Short, lowercase codename.

    .control-group
      = f.label :description, :class => 'control-label'
      .controls
        = f.text_area :description, required: true, placeholder: "Donec sed odio dui. Sed posuere    consectetur est at   lobortis. Cras mattis consectetur purus sit amet fermentum. Donec  ullamcorper   nulla non metus auctor fringilla.", rows: 8
        span class="help-block" Verbose description of the pipeline.
        hr
        = f.submit 'Save', :class => 'btn btn-primary'

    / .form-actions
        

app/views/pipelines/_overview.html.slim
.btn-toolbar
	div class="btn-group"
		- if current_user.is_admin?
			a class="btn dropdown-toggle" data-toggle="dropdown" href="#"
				i.icon-wrench
				|  Tools 
				span class="caret"
			ul class="dropdown-menu"
				li = link_to 'Edit Pipeline', edit_pipeline_path(pipeline)
				li = link_to 'Batch Work Item Import', batch_pipeline_path(pipeline)
				li = link_to 'Manage All Work Items', items_path
		= link_to 'Reports', reports_pipeline_path(pipeline), class: 'btn'
		a.btn.notification-button
			i.notification-icon.icon-bullhorn
			|  Notifications

br



dl.dl-horizontal
	dt Description:
	dd = pipeline.description
	dt Code:
	dd = pipeline.code
	dt Created:
	dd
		= time_ago_in_words pipeline.created_at
		|  ago.
	dt By:
	dd = pipeline.user.email
	dt Stages: 
	dd
		span.badge.badge-success
			= pipeline.stages.count
			|  
		= pipeline.stages.rank(:number).collect{|s| "#{s.name}"}.join(', ')
	dt Active Work items: 
	dd
		span.badge.badge-success
			= Member.active.where(pipeline_id: pipeline.id).count
		|  
		= Member.active.where(pipeline_id: pipeline.id).collect{|m| m.item.name}.join(', ')
	dt API URL:
	dd
		= link_to 'JSON', pipeline_url(pipeline, format: 'json')
		|  
		= link_to 'XML', pipeline_url(pipeline, format: 'xml')

app/views/pipelines/_performance.html.slim
h4
  i.icon-fire
  |  Performance
p.muted This graph shows relative time differences in sequencial stage changes.

.hero-unit Not Yet :(

app/views/pipelines/_recent.html.slim
h4
  i.icon-calendar
  |  Recent Status Updates
p.muted The last ten statuses set are shown here. Note that only the most recent change to a given status is tracked.
- stages = pipeline.stages.rank(:number)
- recent = Status.find(:all, conditions: {stage_id: stages.collect{|s| s.id}, member_id: pipeline.members.collect{|m|m.id}}, order: 'updated_at DESC', limit: 10)
- if recent.size > 0
  table.table.table-striped.table-condensed
	thead
	  tr
		th Item
		th Stage
		th Status
		th User
		th Date
	tbody
	  - recent.each do |r|
		tr
		  td = r.member.item.name
		  td = r.stage.name
		  td = r.code
		  td = r.user.email
		  td
			= time_ago_in_words r.updated_at
			|  ago

app/views/pipelines/_row.html.slim
- m = row
.row-fluid id="member_#{m.id}" class="item-row #{m.archived ? 'archived' : 'active'}" data-item-name="#{m.item.name}" data-project-tags="#{m.item.project_list.join(' ')}"
	.span2
		h4.pull-right
			- ptags = m.item.project_list
			- if current_user.is_admin?
				a.tip href="#{edit_item_path(m.item)}" data-toggle="tooltip" title="" data-original-title="#{m.item.notes} Created #{time_ago_in_words(m.created_at)} ago. Project tags: #{ptags.empty? ? '(none)' : ptags.join(', ')}."
					= m.item.name
			- else
				a.tip data-toggle="tooltip" title="" data-original-title="#{m.item.notes} Created #{time_ago_in_words(m.created_at)} ago. Project tags: #{ptags.empty? ? '(none)' : ptags.join(', ')}."
					= m.item.name
			span.pull-right
				| &nbsp;
				- if m.favorites.where(user_id: current_user).first
					i.favorite-icon.icon-star data-member-id="#{m.id}"
				- else
					i.favorite-icon.icon-star-empty data-member-id="#{m.id}"
				| &nbsp;
				- if m.archived
					i.archive-icon.icon-folder-close data-member-id="#{m.id}"
				- else
					i.archive-icon.icon-folder-open data-member-id="#{m.id}"
				| &nbsp;
				i.tint-icon.icon-tint data-member-id="#{m.id}" data-item-id="#{m.item.id}"
				| &nbsp;

	.span10
		ul.stages.breadcrumbs-one.pull-left
			- pipeline.stages.rank(:number).each do |s|
				- status = Status.where(stage_id: s, member_id: m)[0]
				- code = status.nil? ? Status::DEFAULT : status.code
				- notes = status.nil? ? '' : status.notes
				li.stage data-member-id="#{m.id}" data-stage-id="#{s.id}" data-code="#{code}" data-notes="#{notes}"
					a class="#{code} status-tooltip" rel='tooltip' 
						= s.name


				

app/views/pipelines/_statistics.html.slim
h4
  i.icon-tasks
  |  Pipeline Stage Breakdown
p.muted This chart shows item counts per stage. Stages are ordered from first to last, starting at the top.
- stats = pipeline.statistics
- stages = pipeline.stages.rank(:number)
- stages.each do |s|
	.row-fluid
		.span3
			a.tip data-toggle="tooltip" title="" data-original-title="#{s.description}"
				= s.name
		.span9
		  div class="progress"
		  	- Status::ALL.each do |s_code|
		  		- if s_code != Status::DEFAULT && stats[s.name][s_code].count > 0
					a.tip data-toggle="tooltip" class="bar bar-#{s_code}" title="" data-original-title="#{stats[s.name][s_code].collect{|m|m.item.name}.join(', ')}"  style="width: #{(100.0 * stats[s.name][s_code].count	/ @pipeline.members.count)}%;"
					  = stats[s.name][s_code].count

app/views/pipelines/_status.html.slim
p.muted
	|  Click a stage marker to update its status. Work items with the most recently updated statuses are shown at the top. Click the star icon next to each work item to favorite it, and keep it at the top of the list.

.text-center
	- favorite_members = pipeline.members.select {|m| m.favorites.where(user_id: current_user).first }.sort{|a,b| b.updated_at <=> a.updated_at}
	- other_members = pipeline.members.select {|m| m.favorites.where(user_id: current_user).first.nil? }.sort{|a,b| b.updated_at <=> a.updated_at}
	div#favorite-members
		- if !favorite_members.empty?
			= render partial: 'pipelines/row', locals: {pipeline: pipeline}, collection: favorite_members
	hr
	div#other-members
		= render partial: 'pipelines/row', locals: {pipeline: pipeline}, collection: other_members

app/views/pipelines/_timeline.html.slim
h4
  i.icon-time
  |  Timeline
p.muted This chart shows hotspots of the current pipeline status chronologically.

.hero-unit Not Yet :(

app/views/pipelines/_triggers.html.slim
h4
  i.icon-forward
  | Active Triggers
p.muted This chart shows item counts per stage. Stages are ordered from first to last, starting at the top.

- triggers = Trigger.where(stage_id: [pipeline.stages.collect{|s| s.id}]).all
- if triggers.size > 0
  table.table.table-striped.table-condensed
	thead
	  tr
		th Stage
		th Service
		th Condition
	tbody
	  - triggers.each do |t|
		tr
		  td = t.stage.name
		  td = t.service.name
		  td = t.condition

app/views/pipelines/batch.html.slim
h2 Add a bunch of new work items.
p.help-block
	| Use this form to add new work items en mass to the 
	= @pipeline.name
	|  pipeline. Note that all work item names must be unique within the system, so any duplicates will be skipped automatically. Note that, for safety reasons, there is no "batch delete" feature, so please double check your data before using this form! Each row must create a single item, and must contain two columns for the items "name" and "notes" fields, though the notes string may be empty. Any double-quote characters within each string must be escaped by an additional double quote. (See example.)

h3 Example Data
ul
	li Double-quote every value. (Single quotes won't work!)
	li Escape embedded double-quote characters with an additional double-quote character.
	li No extra whitespace or newline characters.
	li No extra space or tab after the comma on every row.
p.well
		| "Don Cornelius","Creator of the nationally syndicated dance/music franchise ""Soul Train""."
		br
		| "Bob (Robert) Barker","Best known for hosting CBS's ""The Price Is Right"" from 1972 to 2007."
		br
		| "Alan Alda",""
h3 Now It's Your Turn
form action="#{submit_batch_pipeline_path(@pipeline)}" class="form-vertical" method="post"
	input name="authenticity_token" value="#{form_authenticity_token}" type="hidden"
	.control-group
		.controls
			label for="project_tags" Project Tags
			input name="project_tags" placeholder="foo, bar, acme, shazzle"
			p.muted An optional comma-seperated-list of project names to associate with these work items.
	.control-group
		.controls
		label for="data" CSV Data
		textarea type="text" name="data" class="input-block-level" rows="10" required="true"
	input class="btn btn-primary" name="commit" type="submit" value="Submit batch items."

app/views/pipelines/edit.html.slim
- model_class = Pipeline
- model = @pipeline.name

#pipeline-edit
	div
		h1
			| Edit the  
			= @pipeline.name
			|  pipeline.
		p.muted = link_to 'see all pipelines', pipelines_path

	.row
		.span6
			h2 Basics
			= render :partial => "form"
		.span6
			h2 Trigger Summary
			p.muted Edit the corresponding stage to add, update and remove individual triggers.
			table.table.table-condensed
				thead
					tr
						th Stage
						th Condition
						th Service
						th Basic/Extended/User Data
						th Last Processed
				tbody
				- @pipeline.stages.each do |s|
					- s.triggers.each do |t|
						tr
							td = link_to s.name, edit_pipeline_stage_path(s.pipeline, s)
							td = t.condition
							td = link_to t.service.name, edit_service_path(t.service)
							td
								= check_box_tag t.id, 'include_basic', t.service.include_basic, disabled: true
								| &nbsp;
								= check_box_tag t.id, 'include_extended', t.service.include_extended, disabled: true
								| &nbsp;
								= check_box_tag t.id, 'include_data', t.service.include_data, disabled: true

	h2 Stage Configuration
	span.help-block Drag and drop the stages below to rearrange them. Also note the edit and delete buttons!
	= link_to 'Add a stage.', new_pipeline_stage_path(@pipeline), class: 'btn btn-primary'
	
	p
		ul.breadcrumbs-one#pipeline-order data-pipeline-id="#{@pipeline.id}"
			- @pipeline.stages.rank(:number).each do |s|
				li.stage id="stage_#{s.id}" data-stage-id="#{s.id}"
					|  
					= link_to (\
							'<i class="icon-align-justify"> </i> '.html_safe + \
							s.name + \
							" <i class='icon-edit' data-stage-id='#{s.id}'> </i>".html_safe + \
							" <i class='icon-trash' data-stage-id='#{s.id}'> </i>".html_safe),
						'#', class: 'complete disabled'
		
	
	hr
	
	h2 Associated Work Items
	p.help-block Drag and drop work items between the two tables to choose what is in the pipeline. Note that removing 	an item from the pipeline will also delete it's history! In other works, re-adding the item to the pipeline will NOT restore it's old stage statuses.
	p = link_to 'manage all work items', items_path
	p = link_to 'go to dashboard', dashboard_path
	
	- all = Item.all
	- associated = @pipeline.items
	- disassociated = all - associated
	.row-fluid
		.span8.offset2
			input.search-query id="work-item-search" type="text" placeholder="Search"
			.help-block Use this search box search for items based on item name or project tag!
	.row-fluid#work-items
		.span4.offset2.well
			h3 In Pipeline
			/ p.muted All items in this column are currently "flowing" through the pipeline.
			ul.work-item-list.associated
				- associated.each do |i|
					li.tip id="item_#{i.id}" data-item-id="#{i.id}" data-toggle="tooltip" data-original-title="Project tags: #{i.project_list.empty? ? '(none)' : i.project_list}"
						i.icon-align-justify
						|  
						= i.name
						span.hidden
							= i.project_list
		.span4.well
			h3 Not In Pipeline
			/ p.muted None of these items have joined the pipeline.
			ul.work-item-list.disassociated
				- disassociated.each do |i|
					li.tip id="item_#{i.id}" data-item-id="#{i.id}" data-toggle="tooltip" data-original-title="Project tags: #{i.project_list.empty? ? '(none)' : i.project_list}"
						i.icon-align-justify
						|  
						= i.name
						span.hidden
							= i.project_list
		

					

	

app/views/pipelines/index.html.slim
.page-header
  h1 Manage pipelines.
  = link_to 'Create a new pipeline.', new_pipeline_path, :class => 'btn btn-primary'


table class="table table-striped table-hover"
  thead
    tr
      th Name
      th Description
      th Code
      th Created
      th Stages
      th API URL
      th Actions
  tbody
    - @pipelines.each do |pipeline|
      tr
        td = pipeline.name
        td = pipeline.description
        td = pipeline.code
        td
          = time_ago_in_words pipeline.created_at
          |  ago.
        td = pipeline.stages.collect{|s| s.name}.join(', ')
        td
          = link_to 'JSON', pipeline_url(pipeline, format: 'json')
          |  
          = link_to 'XML', pipeline_url(pipeline, format: 'xml')
        td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_pipeline_path(pipeline), :class => 'btn btn-mini'
          '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), pipeline_path(pipeline), :method => :delete, :data => { :confirm => 'If you delete this pipeline, work items will NOT be deleted, but their association with this pipeline, including all stage statuses, will be irrevokably deleted. Are you 100% sure you want to do this? ' }, :class => 'btn btn-mini btn-danger'

app/views/pipelines/new.html.slim
.span6.offset3
	div class="page-header"
	  h1 Create a new pipeline.
	= render :partial => "form"
	

app/views/pipelines/reports.html.slim
#reports

	h1
		= @pipeline.name
		|  Reports
	
	
	hr

	.row-fluid
		.span6
			div#chart1 style="width: 100%; height: 100%;"



		.span6#chart2
	
	.row-fluid
		.span6#statistics
			= render partial: 'pipelines/statistics', locals: {pipeline: @pipeline}
		.span6#recent
			= render partial: 'pipelines/recent', locals: {pipeline: @pipeline}

	.row-fluid
		.span6#triggers
			= render partial: 'pipelines/triggers', locals: {pipeline: @pipeline}
	.row-fluid
		.span6#triggers
			= render partial: 'pipelines/performance', locals: {pipeline: @pipeline}
		.span6#timeline
			= render partial: 'pipelines/timeline', locals: {pipeline: @pipeline}