config/routes.rb
PipeCleaner::Application.routes.draw do


	resources :notifications do
		collection do
			get 'user', as: :user_notifications
			put 'user_update', as: :user_notifications_update
		end

	end


	resources :services do
		member do
			get 'test'
		end
	end
	
	resources :favorites
	resources :delayed_jobs

	match "/documents/:file_or_folder", :controller => :documents, :action => :get_file, :file_or_folder => /.*/
	resources :documents, :only => :get_file

	devise_for :users
	resources :users

	get 'manage' => 'users#manage'

	resources :pipelines do
		member do
			get 'reports'
		end
		resources :stages do
		  resources :triggers
		end
		member do
			put	'reorder'
			get 'overview'
			get 'status'
			get 'statistics'
			get 'recent'
			put 'active'
			get 'batch'
			post 'batch' => 'pipelines#submit_batch', as: :submit_batch
			post 'favorite'
			delete 'unfavorite'
		end
		resources :members do
			member do
				put 'archive'
				put 'unarchive'
			end
		end
	end


	resources :statuses do
		collection do
			post 'advance'
			put	'ping'
		end
	end
	resources :items do
		member do
			put 'associate'
			put 'disassociate'
			get 'data'
		end
		collection do
			get 'find'
		end
	end
	resources :pipelines


	get 'welcome' => "welcome#landing",  as: 'landing'
	get 'dashboard' => "welcome#dashboard", as: 'dashboard'
	get 'api' => "welcome#api",  as: 'api'
	get 'integration' => "welcome#integration",  as: 'integration'
	get 'guide' => 'welcome#guide',	as: 'guide'
	get 'terms' => 'welcome#terms',	as: 'terms'
	get 'queue' => 'welcome#queue', as: 'queue'
	get 'mashup' => 'welcome#mashup', as: 'mashup'

	# User management.
	get 'manage' => 'users#manage'
	post 'manage/:user_id/deny' => 'users#deny', as: :deny_user
	post 'manage/:user_id/approve' => 'users#approve', as: :approve_user
	put  'manage/:user_id' => 'users#update', as: :update_user
	post 'manage/:user_id/transfer' => 'users#transfer', as: :transfer_ownership
	post 'manage/:user_id/regenerate_api_token' => 'users#regenerate', as: :regenerate

	root :to => "welcome#landing"

	# rails_admin
	mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'


end

app/models/stage.rb
class Stage < ActiveRecord::Base

	extend FriendlyId
	friendly_id	:name, use: :slugged

	# Uses the ranked-model gem.
	include RankedModel
	ranks :number, with_same: :pipeline_id

	belongs_to	:pipeline

	has_many	:statuses,		dependent: :destroy
	has_many	:triggers,		dependent: :destroy, :before_add => :set_nest
	has_many	:notifications,	dependent: :destroy

	accepts_nested_attributes_for	:triggers, allow_destroy: true

	validates_presence_of	:pipeline
	validates_numericality_of	:number, only_integer: true, greater_than_or_equal_to: 0
	validates_uniqueness_of	:name,	scope: [:pipeline_id]

	attr_accessible :pipeline, :description, :name, :pipeline_id, :number, :triggers_attributes


	private

	# http://stackoverflow.com/questions/2611459/ruby-on-rails-nested-attributes-how-do-i-access-the-parent-model-from-child-m
	def set_nest(trigger)
		trigger.stage ||= self
	end

end

app/controllers/stages_controller.rb
class StagesController < InheritedResources::Base

	before_filter :authenticate_user!,  except: [:landing]
	before_filter :set_session_pipeline_from_params

	load_and_authorize_resource

	def new
		@stage = Stage.new
		@stage.pipeline = @pipeline
		respond_to do |format|
			format.html # new.html.erb
			format.json { render json: @stage }
		end
	end

	def create
		# @pipeline = Pipeline.friendly.find(params[:pipeline_id])
		puts "P: #{@pipeline.name}"
		@stage = Stage.new(params[:stage])
		@stage.number = @pipeline.stages.count
		@stage.pipeline = @pipeline
		create! { edit_pipeline_path(@stage.pipeline) }
	end

	def update
		puts "P: #{@pipeline.name}"
		puts "P: #{@stage.pipeline.name}"
		update! { edit_pipeline_path(@stage.pipeline) }
	end

end

app/helpers/stages_helper.rb
module StagesHelper
end

app/views/stages/_form.html.slim
= form_for([@stage.pipeline, @stage], html: {class: 'form'}) do |f|
	- if @stage.errors.any?
		#error_explanation
			h2 = "#{pluralize(@stage.errors.count, "error")} prohibited this stage from being saved:"
			ul
				- @stage.errors.full_messages.each do |message|
					li = message
	.row-fluid
		.span6
			.actions = f.submit 'Save', class: 'btn btn-primary'
			.field
				= f.label :name
				= f.text_field :name, required: true
			.field
				= f.label :description
				= f.text_area :description
		.span6
	
			h2 Triggers
			#triggers
				= f.fields_for :triggers do |builder|
					= render 'stages/trigger_fields', f: builder, parent_id: builder.object.id
				.links
					= link_to_add_association text_with_icon('Add Trigger', 'plus'), f, :triggers, class: 'btn'


	
	

app/views/stages/_trigger_fields.html.slim
.nested-fields.row.well
	.span6
		.control-group
			= f.label :service_id, class: 'control-label'
			.controls
				= f.select :service_id, options_for_select(Service.all.collect{|s| [s.name, s.id]}, selected: f.object.service_id)
				/ = throw :fit
		.control-group
			= f.label :condition, class: 'control-label'
			.controls
				= f.select :condition, Status::ALL, required: true, selected: f.object.condition
	.span6
		.control-group.pull-right
			.controls
				= link_to_remove_association text_with_icon('Remove Trigger', 'trash'), f, class: 'btn btn-danger'
		
		- if !f.object.id.nil?
			dl.dl-horizontal
				dt ID
				dd = f.object.id unless f.object.id.nil?
				dt Created
				dd
					= time_ago_in_words(f.object.created_at) unless f.object.created_at.nil?
				dt Updated
				dd
					= time_ago_in_words f.object.updated_at unless f.object.updated_at.nil?

app/views/stages/edit.html.slim
h1
	| Editing "
	= @stage.name
	| " Stage
p.muted
	| (Part of the 
	= @stage.pipeline.name
	|  pipeline.)

== render 'form'

app/views/stages/index.html.slim
h1 Listing stages

table
	tr
		th Pipeline
		th Name
		th Description
		th Actions

	- @stages.each do |stage|
		tr
			td = stage.pipeline_id
			td = stage.name
			td = stage.description
			td
				= link_to 'Show', pipeline_stage_path(stage.pipeline, stage)
				= link_to 'Edit', edit_pipeline_stage_path(stage.pipeline, stage)
				= link_to 'Destroy', [stage.pipeline, stage], :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Stage', new_pipeline_stage_path(@pipeline)

app/views/stages/new.html.slim
/ .span6.offset3

h1 Add a stage.
p.muted
	| (Will be added to the 
	= @pipeline.name
	|  pipeline.)

== render 'form'

app/views/stages/show.html.slim
p#notice = notice

p
  strong Pipeline:
  = @stage.pipeline_id
p
  strong Name:
  = @stage.name
p
  strong Description:
  = @stage.description

= link_to 'Edit', edit_stage_path(@stage), class: 'btn'