config/routes.rb
PipeCleaner::Application.routes.draw do


	resources :notifications do
		collection do
			get 'user', as: :user_notifications
			put 'user_update', as: :user_notifications_update
		end

	end


	resources :services do
		member do
			get 'test'
		end
	end
	
	resources :favorites
	resources :delayed_jobs

	match "/documents/:file_or_folder", :controller => :documents, :action => :get_file, :file_or_folder => /.*/
	resources :documents, :only => :get_file

	devise_for :users
	resources :users

	get 'manage' => 'users#manage'

	resources :pipelines do
		member do
			get 'reports'
		end
		resources :stages do
		  resources :triggers
		end
		member do
			put	'reorder'
			get 'overview'
			get 'status'
			get 'statistics'
			get 'recent'
			put 'active'
			get 'batch'
			post 'batch' => 'pipelines#submit_batch', as: :submit_batch
			post 'favorite'
			delete 'unfavorite'
		end
		resources :members do
			member do
				put 'archive'
				put 'unarchive'
			end
		end
	end


	resources :statuses do
		collection do
			post 'advance'
			put	'ping'
		end
	end
	resources :items do
		member do
			put 'associate'
			put 'disassociate'
			get 'data'
		end
		collection do
			get 'find'
		end
	end
	resources :pipelines


	get 'welcome' => "welcome#landing",  as: 'landing'
	get 'dashboard' => "welcome#dashboard", as: 'dashboard'
	get 'api' => "welcome#api",  as: 'api'
	get 'integration' => "welcome#integration",  as: 'integration'
	get 'guide' => 'welcome#guide',	as: 'guide'
	get 'terms' => 'welcome#terms',	as: 'terms'
	get 'queue' => 'welcome#queue', as: 'queue'
	get 'mashup' => 'welcome#mashup', as: 'mashup'

	# User management.
	get 'manage' => 'users#manage'
	post 'manage/:user_id/deny' => 'users#deny', as: :deny_user
	post 'manage/:user_id/approve' => 'users#approve', as: :approve_user
	put  'manage/:user_id' => 'users#update', as: :update_user
	post 'manage/:user_id/transfer' => 'users#transfer', as: :transfer_ownership
	post 'manage/:user_id/regenerate_api_token' => 'users#regenerate', as: :regenerate

	root :to => "welcome#landing"

	# rails_admin
	mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'


end

app/models/item.rb
class Item < ActiveRecord::Base

	acts_as_taggable
	acts_as_taggable_on	:projects

	has_many	:members,	dependent: :destroy
	has_many	:pipelines,	through: :members
	belongs_to	:user,	foreign_key: :created_by

	validates_presence_of	:user
	validates_presence_of	:name
	validates_uniqueness_of	:name

	attr_accessible :name, :notes, :user, :project_list

	before_save :default_values

	def default_values
		self.data = '{}' if self.data.nil? || self.data == ''
	end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

	before_filter :authenticate_user!
	load_and_authorize_resource

	def associate
		member = Member.where(item_id: params[:id], pipeline_id: params[:pipeline_id]).first
		if member
			# Already exists!
		else
			member = Member.new(item_id: params[:id], pipeline_id: params[:pipeline_id])
		end
		member.save!
		respond_to do |format|
			format.json { head :no_content }
			format.xml { head :no_content }
		end
	end

	def disassociate
		member = Member.where(item_id: params[:id], pipeline_id: params[:pipeline_id]).first
		if member
			member.destroy
		end
		respond_to do |format|
			format.json { head :no_content }
			format.xml { head :no_content }
		end
	end

	# GET /items
	# GET /items.json
	def index
		@items = Item.paginate(:page => params[:page], :per_page => 10)

		respond_to do |format|
			format.html # index.html.erb
			format.json { render json: @items }
			format.xml { render xml: @items }
		end
	end
	
	def data
		@item = Item.find(params[:id])
		render layout: false
	end

	def find
		if(params[:like].nil?)
			items = Item.where(name: params[:name])
		else
			items = Item.where("name like ?", "%#{params[:name]}%")
		end
		respond_to do |format|
			# format.html # show.html.erb
			format.json { render json: items, include: {:members => {include: [:pipeline, :statuses]}} }
			format.xml { render xml: items, include: {:members => {include: [:pipeline, :statuses]}} }
		end
	end


	# GET /items/1
	# GET /items/1.json
	def show
		@item = Item.find(params[:id])

		respond_to do |format|
			format.html # show.html.erb
			format.json { render json: @item }
			format.xml { render xml: @item }
		end
	end

	# GET /items/new
	# GET /items/new.json
	def new
		@item = Item.new

		respond_to do |format|
			format.html # new.html.erb
			format.json { render json: @item }
		end
	end

	# GET /items/1/edit
	def edit
		@item = Item.find(params[:id])
	end

	# POST /items
	# POST /items.json
	def create
		@item = Item.new(params[:item])
		@item.user = current_user
		respond_to do |format|
			if @item.save
				format.html { redirect_to items_path, notice: 'Item was successfully created.' }
				format.json { render json: @item, status: :created, location: @item }
				format.xml { render xml: @item, status: :created, location: @item }
			else
				format.html { render action: "new" }
				format.json { render json: @item, status: :unprocessable_entity }
				format.xml { render xml: @item, status: :unprocessable_entity }
			end
		end
	end

	# PUT /items/1
	# PUT /items/1.json
	def update
		@item = Item.find(params[:id])

		respond_to do |format|
			if @item.update_attributes(params[:item])
				format.html { redirect_to items_path, notice: 'Item was successfully updated.' }
				format.json { head :no_content }
			else
				format.html { render action: "edit" }
				format.json { render json: @item.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /items/1
	# DELETE /items/1.json
	def destroy
		@item = Item.find(params[:id])
		@item.destroy

		respond_to do |format|
			format.html { redirect_to items_url }
			format.json { head :no_content }
		end
	end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.slim
= form_for @item, :html => { :class => "form-horizontal" } do |f|

  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :placeholder => 'Another Work Item', required: true
  .control-group
    = f.label :project_list, :class => 'control-label'
    .controls
      = f.text_field :project_list, :placeholder => 'optional, project, tags', required: false
  .control-group
    = f.label :notes, :class => 'control-label'
    .controls
      = f.text_area :notes, :class => 'text_area', placeholder: "Optional freeform text of your choice..."
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'

app/views/items/data.html.slim
h2 = @item.name

p Every work item's data blob is syntactically-valid, UTF-8-encoded JSON. The size of the entire structure must be kept to larger than 100KB in size. In other words, it's for general message passing between services and NOT a data storage or archiving solution. Do not abuse the blob! Blob does not like abuse!

pre
	= @item.data

app/views/items/edit.html.slim
.span6.offset3
	.page-header
		h1
			| Editing 
			= @item.name
			|  work item.
	= render :partial => "form"
	

app/views/items/index.html.slim
- model_class = Item
div class="page-header"
  h1 All work items.
  p
    | PipeCleaner has 
    = Item.count
    |  work items.
  = link_to "Create a work item.", new_item_path, :class => 'btn btn-primary'

= will_paginate @items

table class="table table-striped table-condensed table-hover"
  thead
    tr
      th Name
      th Pipelines
      th Project Tags
      th Notes
      th Contributor
      th Created
      th API URL
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @items.each do |item|
      tr
        td= item.name
        td= item.pipelines.collect{|p| link_to(p.name, edit_pipeline_path(p))}.join(', ').html_safe
        td= item.project_list
        td= item.notes
        td= item.user.email
        td= item.created_at
        td
          = link_to 'JSON', item_url(item, format: 'json')
          |  
          = link_to 'XML', item_url(item, format: 'xml')
        td
          = link_to  t('.edit', :default => t("helpers.links.edit")), edit_item_path(item), :class => 'btn btn-mini'
          '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), item_path(item), :method => :delete, :data => { :confirm => "This will removing all associations with existing pipelines, including status information, before removing the work item. This is irrevokable. Are you sure?"}, :class => 'btn btn-mini btn-danger'

= will_paginate @items

app/views/items/new.html.slim
.span6.offset3
	.page-header
	  h1 Create a new work item.
	= render :partial => "form"

app/views/items/show.html.slim
- model_class = Item
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human

p
  strong= model_class.human_attribute_name(:name) + ':'
  br
  = @item.name
p
  strong= model_class.human_attribute_name(:notes) + ':'
  br
  = @item.notes

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), items_path, :class => 'btn'
  '
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_item_path(@item), :class => 'btn'
  '
  = link_to t('.destroy', :default => t("helpers.links.destroy")), item_path(@item), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'